# user input
print("Hi, What is your name? ")
name = input()
print("What is your age? ")
age = input()
print("What is your DOB? ")
dob = input()
print("What is your Address? ")
address = input()
print(f"Hi {name}, you are {age} yeras old and you were born on {dob} and live at {address}")
print("Hi " + name + ". You are " + age + " and you were born on " + dob)
